spring.application.name=taskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.deserialization.fail-on-unknown-properties=true


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:3f8a2b1c9d7e4f6a0b5c8d2e1f3a7b9c4d6e8f0a2b4c6d8e0f1a3b5c7d9e1f3a}
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

#minio.url=http://localhost:9000
#minio.access-key=minioadmin
#minio.secret-key=minioadmin
#minio.bucket-name=taskmanager-docs


minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=${MINIO_BUCKET_NAME:taskmanager-docs}